name: Build Linux binary

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
      - name: Build binary with PyInstaller
        run: |
          # Bundle the assets folder into the single-file binary (POSIX uses ':' separator)
          # Do NOT include save data (shogi_kifu.csv) — it should remain external
          pyinstaller --onefile --noconsole \
            --add-data "assets:assets" \
            shogigame.py
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: shogigame-linux-binary
          path: dist/shogigame